"""
示例管道配置文件，用于获取A股历史数据
"""
pipeline_id: "stock_zh_a_hist_pipeline"
fetcher_type: "akshare"
interface_name: "ak_stock_zh_a_hist"
interface_params:
  symbol: "000001"  # 平安银行
  period: "daily"
  start_date: "20230101"
  end_date: "20231231"
  adjust: "qfq"  # 前复权

cleaner_type: "standard"
cleaner_config:
  column_mapping:
    "日期": "trade_date"
    "开盘": "open_price"
    "收盘": "close_price"
    "最高": "high_price"
    "最低": "low_price"
    "成交量": "volume"
    "成交额": "amount"
    "振幅": "amplitude"
    "涨跌幅": "change_percent"
    "涨跌额": "change_amount"
    "换手率": "turnover_rate"
  date_columns: ["trade_date"]
  numeric_columns: ["open_price", "close_price", "high_price", "low_price", "volume", "amount", "amplitude", "change_percent", "change_amount", "turnover_rate"]
  fill_na: true

transformer_config:
  schema_mapping:
    "ak_stock_zh_a_hist":
      table_name: "stock_market_data"
      interface_id: 1
      column_mapping:
        "trade_date": "trade_date"
        "open_price": "open_price"
        "close_price": "close_price"
        "high_price": "high_price"
        "low_price": "low_price"
        "volume": "volume"
        "amount": "amount"
        "amplitude": "amplitude"
        "change_percent": "change_percent"
        "change_amount": "change_amount"
        "turnover_rate": "turnover_rate"

comparator_config:
  key_columns:
    "stock_market_data": ["trade_date", "stock_code"]
  compare_all_columns: false

store_config:
  batch_size: 1000
  retry_count: 3
  unique_constraints:
    "stock_market_data": ["trade_date", "stock_code"]

# 添加股票代码
key_columns: ["trade_date", "stock_code"]
